export const CHNAGE_USER_INFO = 'CHNAGE_USER_INFO'
export const CHNAGE_USER_TOKEN = 'CHNAGE_USER_TOKEN'
export const CHNAGE_USER_IDENTITY = 'CHNAGE_USER_IDENTITY'

// 个人中心
export const CHNAGE_ELECTRONIC_CARD_INFO = 'CHNAGE_ELECTRONIC_CARD_INFO'

// app
export const CHANGE_IS_IN_MINIPROGRAM = 'CHANGE_IS_IN_MINIPROGRAM'
export const CHANGE_SYSTERM_INFO = 'CHANGE_SYSTERM_INFO'
export const CHANGE_SYSTERM_TERMINAL = 'CHANGE_SYSTERM_TERMINAL'
